from django.shortcuts import render

from django.core.mail import send_mail,EmailMessage

#from mailer import send_mail
'''
def home (request):
    send_mail(
    'Test Email dengan Django',
    'Test email baru',
    'admin.tableau@aski.component.astra.co.id',
    ['eko.pujiyanto@aski.component.astra.co.id'],
    fail_silently=False,
    )
      mail.send(
        'eko.pujiyanto@aski.component.astra.co.id', # List of email addresses also accepted
        'admin.tableau@aski.component.astra.co.id',
        subject='My email',
        message='Hi there!',
        html_message='Hi <strong>there</strong>!',
    )

    context ={
        'judul' : 'Home Page',              
    }    
    return render(request, 'home.html', context)
    '''
#from post_office import mail
def home (request):

    if request.method == 'POST':
        '''
        send_mail(
        'Test Email dengan Django',
        'Test email baru',
        'online.approval@aski.component.astra.co.id',
        ['linovri.pratama@aski.component.astra.co.id','kojiya.te.ugm@gmail.com','novriarmeza@gmail.com','eko.pujiyanto@aski.component.astra.co.id'],
        fail_silently=False,
        )'''
        email_body = """\
            <html>
            <head>Purchase Request Approval</head>
            <body>

            <p>This purchase request needs your approval </>
            <br>
            <p> item PR disini</p>
            <br>

            <table width="100%" cellspacing="0" cellpadding="0">
                <tr>
                    <td>
                        <table cellspacing="0" cellpadding="0">
                            <tr>
                                <td style="border-radius: 2px;width : 150px;text-align: center;" bgcolor="#4bf542">
                                    <a href="mailto:online.approval@aski.component.astra.co.id?subject=Approve:ASKIPR0001" target="_blank" style="padding: 8px 12px; border: 1px solid #4bf542;border-radius: 2px;font-family: Helvetica, Arial, sans-serif;font-size: 14px; color: #ffffff;text-decoration: none;font-weight:bold;display: inline-block;">
                                        APPROVE             
                                    </a>
                                </td>
                                <td>&nbsp;&nbsp;</td>
                                <td style="border-radius: 2px;width: 150px;text-align: center;" bgcolor="#ED2939">
                                    <a href="mailto:online.approval@aski.component.astra.co.id?subject=Reject:ASKIPR0001&body=Purchase Request Reject Message:" target="_blank" style="padding: 8px 12px; border: 1px solid #ED2939;border-radius: 2px;font-family: Helvetica, Arial, sans-serif;font-size: 14px; color: #ffffff;text-decoration: none;font-weight:bold;display: inline-block;">
                                        REJECT             
                                    </a>
                                </td>
                                <td>&nbsp;&nbsp;</td>
                                <td style="border-radius: 2px;width: 150px;text-align: center;" bgcolor="#ebde34">
                                    <a href="mailto:online.approval@aski.component.astra.co.id?subject=NeedRevise:ASKIPR0001&body=Purchase Request Revision Message:" target="_blank" style="padding: 8px 12px; border: 1px solid #ebde34;border-radius: 2px;font-family: Helvetica, Arial, sans-serif;font-size: 14px; color: #000000;text-decoration: none;font-weight:bold;display: inline-block;">
                                        REVISE             
                                    </a>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
            
            <br>
            <i>This email automatically generated by Online Approval System PT Astra Komponen Indonesia<i>


            </body>
            </html>
            """ #% (user, message, email)
        #email = EmailMessage('A new mail!', email_body, to=['eko.pujiyanto@aski.component.astra.co.id'])
        #email.content_subtype = "html" # this is the crucial part 
        #email.send()
        send_mail(
        'Test Email dengan Django',
        'Test email baru',
        'online.approval@aski.component.astra.co.id',
        ['eko.pujiyanto@aski.component.astra.co.id'],
        fail_silently=False,
        html_message=email_body,
        )
  
    context ={
        'judul' : 'Home Page',              
    }    
    return render(request, 'home.html', context)
